version: 2

sources:
  - name: raw # Alias used in dbt: {{ source('raw', 'sales') }}
    schema: gz_raw_data # Actual BigQuery dataset name
    tables:
      - name: sales
        identifier: raw_gz_sales
      - name: product
        identifier: raw_gz_product
      - name: ship
        identifier: raw_gz_ship
